services:
  backend:
    build: ./server
    volumes:
      - ./server/src/database/mychat.db:/app/src/database/mychat.db
    expose:
      - 5000
    networks:
      - app-network
  
  frontend:
    build: ./client
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt/live/mkstech.dev/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/mkstech.dev/privkey.pem:/etc/nginx/certs/privkey.pem
    depends_on:
      - backend
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge