services:
  backend:
    build: ./server
    volumes:
      - ./server/database/mychat.db:/src/database/mychat.db
    expose:
      - 5000
    networks:
      - app-network
  
  frontend:
    build: ./client
    expose:
      - 80
    depends_on:
      - backend
    networks:
      - app-network
  
  nginx:
    image: nginx:alpine
    ports:
      - "90:90"
    volumes:
      - ./client/build:/usr/share/nginx/html
      - ./client/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge